# Generated by Django 5.0 on 2023-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='lado',
            field=models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita')], default='left', max_length=16, verbose_name='Lado'),
        ),
    ]
